from fastapi import FastAPI, Depends, HTTPException, Request, Form
from fastapi.responses import RedirectResponse, JSONResponse
from sqlalchemy.orm import Session
import time
import models
import schemas
import crud
# from starlette.middleware.sessions import SessionMiddleware #pip install starlette
from database import engine, SessionLocal
from fastapi.templating import Jinja2Templates
from passlib.context import CryptContext # PASSWORD HASHER(pip install passlib[bcrypt])
from routes.auth import router as auth_router
from routes.home import router as home_router
from routes.jwtauth import router as jwt_router
from routes.user import router as user_router
from routes.simplecrud import router as crud_router
from routes.crudimage import router as crud_image
from routes.email import router as email_router
from routes.req import router as req_router
from routes.sms import router as sms_router
from routes.payment import router as pay_router
from routes.paystack import router as paystack_router
from routes.flutterwave import router as flutterwave_router
from routes.stripe import router as stripe_router
from routes.otp import router as otp_router
from routes.websocket import router as socket_router
from routes.httpclient import router as client_router
# from pydantic import BaseModel
from fastapi.staticfiles import StaticFiles
from starlette.middleware.sessions import SessionMiddleware
#redis for rate limiting
from slowapi import Limiter
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded


templates = Jinja2Templates(directory="templates")

# CREATE TABLES
models.Base.metadata.create_all(bind=engine)

# class Item(BaseModel):
#     name: str
#     description: str | None = None
#     price: float
#     tax: float | None = None


# API
description = """
ChimichangApp API helps you do awesome stuff. 🚀

## Items

You can **read items**.

## Users

You will be able to:

* **Create users** (_not implemented_).
* **Read users** (_not implemented_).
"""


# FASTAPI INSTANCE
app = FastAPI(
    title="ChimichangApp",
    description=description,
    summary="Deadpool's favorite app. Nuff said.",
    version="0.0.1",
    terms_of_service="http://example.com/terms/",
    contact={
        "name": "Deadpoolio the Amazing",
        "url": "http://x-force.example.com/contact/",
        "email": "dp@x-force.example.com",
    },
    license_info={
        "name": "Apache 2.0",
        "url": "https://www.apache.org/licenses/LICENSE-2.0.html",
    },
)

# RATE LIMITER
limiter = Limiter(key_func=get_remote_address)
app.state.limiter = limiter


# upload static files
app.mount(
    "/uploads",
    StaticFiles(directory="uploads"),
    name="uploads"
)

app.add_middleware(
    SessionMiddleware,
    secret_key="super-secret-key"
)
# REGISTER ROUTES
app.include_router(auth_router)
app.include_router(home_router)
app.include_router(jwt_router)
app.include_router(user_router)
app.include_router(crud_router)
app.include_router(crud_image)
app.include_router(email_router)
app.include_router(req_router)
app.include_router(sms_router)
app.include_router(pay_router)
app.include_router(paystack_router)
app.include_router(flutterwave_router)
app.include_router(stripe_router)
app.include_router(otp_router)
app.include_router(socket_router)
app.include_router(client_router)
# PASSWORD HASHER
pwd_context = CryptContext(
    schemes=["bcrypt"],
    deprecated="auto"
)


# DATABASE CONNECTION
def get_db():

    db = SessionLocal()

    try:
        yield db
    finally:
        db.close()


# @app.middleware("http")
# async def add_process_time_header(request: Request, call_next):
#     # 1. Start timer BEFORE the request is processed
#     start_time = time.perf_counter()
    
#     # 2. Pass the request to the next handler (your actual route)
#     # call_next() returns the response generated by the route
#     response = await call_next(request)
    
#     # 3. End timer AFTER the response is generated
#     process_time = time.perf_counter() - start_time
    
#     # 4. Add a custom header to the response
#     # Note: Use 'X-' prefix for custom headers
#     response.headers["X-Process-Time"] = str(process_time)
    
#     return response


@app.middleware("http")
async def log_requests(request: Request, call_next):

    start_time = time.time()

    print(f"Incoming request: {request.method} {request.url}")

    response = await call_next(request)

    process_time = time.time() - start_time

    print(f"Completed in {process_time:.2f}s")

    return response


# Rate Limiting Middleware
request_log = {}
LIMIT = 5  # max requests
WINDOW = 10  # time window in seconds


@app.middleware("http")
async def rate_limit_middleware(request: Request, call_next):

    client_ip = request.client.host
    current_time = time.time()

    # initialize user record
    if client_ip not in request_log:
        request_log[client_ip] = []

    # remove old requests outside window
    request_log[client_ip] = [
        timestamp for timestamp in request_log[client_ip]
        if current_time - timestamp < WINDOW
    ]

    # check limit
    if len(request_log[client_ip]) >= LIMIT:

        return JSONResponse(
            status_code=429,
            content={
                "detail": "Too many requests. Please slow down."
            }
        )

    # add current request
    request_log[client_ip].append(current_time)

    response = await call_next(request)

    return response

# HOME ROUTE
@app.get("/")
def home(request: Request):
    return templates.TemplateResponse(request, "index.html")





# @app.post("/items/")
# async def create_item(item: Item):
#     return item

fake_items_db = [{"item_name": "Foo"}, {"item_name": "Bar"}, {"item_name": "Baz"}]

@app.get("/item/")
async def read_item(skip: int = 0, limit: int = 10):
    return fake_items_db[skip : skip + limit]

# @app.get("/show")
# def shown(request: Request):

#     return templates.TemplateResponse(
#         "index.html",
#         {"request": request}
#     )

@app.get("/items/{item_id}")
async def read_item(item_id: str):
    return {"item_id": item_id}


@app.get("/userz")
async def read_users():
    return ["Rick", "Morty"]



# CREATE USER
@app.post("/users")
def create_user(
    name: str = Form(...),
    email: str = Form(...),
    db: Session = Depends(get_db)
):

    user = models.User(
        name=name,
        email=email
    )

    db.add(user)
    db.commit()

    return {
        "message": "User created"
    }
# @app.post("/users", response_model=schemas.User)
# def create_user(
#     user: schemas.UserCreate,
#     db: Session = Depends(get_db)
# ):
#     return crud.create_user(db, user)

# # GET ALL USERS
@app.get("/users", response_model=list[schemas.User])
def get_users(db: Session = Depends(get_db)):
    return crud.get_users(db)

# GET SINGLE USER
@app.get("/users/{user_id}", response_model=schemas.User)
def get_user(
    user_id: int,
    db: Session = Depends(get_db)
):

    user = crud.get_user(db, user_id)

    if not user:
        raise HTTPException(
            status_code=404,
            detail="User not found"
        )

    return user

# UPDATE USER
@app.put("/users/{user_id}", response_model=schemas.User)
def update_user(
    user_id: int,
    user: schemas.UserCreate,
    db: Session = Depends(get_db)
):

    updated_user = crud.update_user(
        db,
        user_id,
        user
    )

    if not updated_user:
        raise HTTPException(
            status_code=404,
            detail="User not found"
        )

    return updated_user

# DELETE USER
@app.delete("/users/{user_id}")
def delete_user(
    user_id: int,
    db: Session = Depends(get_db)
):

    deleted_user = crud.delete_user(
        db,
        user_id
    )

    if not deleted_user:
        raise HTTPException(
            status_code=404,
            detail="User not found"
        )

    return {"message": "User deleted"}

